AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Cloud configuration file for CEG 3120.  This template will build three Ubuntu servers with individual project package needs.
Parameters:
  UbuntuInstanceType:
    Description: Ubuntu Server instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: ' The IP address range that can be used to access the EC2 instance'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Mappings:
  AWSInstanceType2Arch:  # Supported architectures (x64bit only)
    # only care about micro
    #t2.small:
      #Arch: HVM64
    #t2.small:
      #Arch: HVM64
    t2.micro:
      Arch: HVM64
  AWSRegionUbuntu: # AMI for Ubuntu server in each supported region 
    us-east-1:   # N. Virginia
      PV64: NOT_SUPPORTED
      HVM64: ami-07d0cf3af28718ef8
      HVMG2: NOT_SUPPORTED
    us-east-2:   # Ohio
      PV64: NOT_SUPPORTED
      HVM64: NOT_SUPPORTED
      HVMG2: NOT_SUPPORTED
  #  us-west-1:   # N. California
  #    PV64: NOT_SUPPORTED
  #    HVM64: NOT_SUPPORTED
  #    HVMG2: NOT_SUPPORTED
  #  us-west-2:   # Oregon
  #    PV64: NOT_SUPPORTED
  #    HVM64: NOT_SUPPORTED
  #    HVMG2: NOT_SUPPORTED
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG3120 VPC
  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG3120 Subnet
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  RouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  Route:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  SubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable
  # will also have 3 servers, keeping naming convention here
  # Resource out IP per instance
  Ubuntu1IPAddress:
    Type: 'AWS::EC2::EIP'
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
      InstanceId: !Ref Ubuntu1Instance
  Ubuntu2IPAddress:
    Type: 'AWS::EC2::EIP'
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
      InstanceId: !Ref Ubuntu2Instance
  Ubuntu3IPAddress:
    Type: 'AWS::EC2::EIP'
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
      InstanceId: !Ref Ubuntu3Instance
  # TODO: Setup the security groups needed by our machines
  # SSH, LDAP, HTTP, HTTPS
  LinuxSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Enable SSH access via port 22 and LDAP via port 389/636
      GroupName: CEG3120 Project 2 Security Group
      SecurityGroupIngress:
        # Home CIDR
        - IpProtocol: -1
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: 75.186.40.190/32
        # WSU CIDR
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 130.108.0.0/16
        #  Private Network CIDR
        - IpProtocol: tcp #SSH
          FromPort: '22'
          ToPort: '22'
          CidrIp: 10.0.0.0/24
        - IpProtocol: tcp # HTTP
          FromPort: '80'
          ToPort: '80'
          CidrIp: 10.0.0.0/24
        - IpProtocol: -1
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: 10.0.0.0/24 # Above is Redundant but safety net
         # May be wise to go back to top where SSHLocation "variable" was made
        - IpProtocol: tcp  #HTTP
          FromPort: '80'
          ToPort: '80'
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp  #HTTPS
          FromPort: '443'
          ToPort: '443'
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp  #SSH
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation 
        - IpProtocol: tcp # LDAP/OpenLDAP
          FromPort: '389'
          ToPort: '389'
          CidrIp: !Ref SSHLocation 
        - IpProtocol: tcp # LDAP/OpenLDAP
          FromPort: '636'
          ToPort: '636'
          CidrIp: !Ref SSHLocation
  # Tie an instance to an instance type available in the region
  # TODO: Modify / append the following two instances for our usage
  #   Adjust key / value pairs to reflect systems we are creating
  Ubuntu1Instance:
    Type: 'AWS::EC2::Instance'
    DependsOn: AttachGateway
    Properties:
      ImageId: !FindInMap 
        - AWSRegionUbuntu
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref UbuntuInstanceType
          - Arch
      InstanceType: !Ref UbuntuInstanceType
      KeyName: !Ref KeyName
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG3120 LDAP
      NetworkInterfaces:
        - GroupSet:
            - !Ref LinuxSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref Subnet
          PrivateIpAddress: 10.0.0.20
      # Implement Meaningful conventions
      # Implement public key link for proxy
        # wget https://raw.githubusercontent.com/BDDave-Student/dave-ceg3120-student/master/project2/CloudFormations/haproxy_key.pub && \      # mv index-serv2.html /var/www/html/index.html && \
        # cat haproxy_key.pub >> /home/ubuntu/.ssh/authorized_keys
        # rm haproxy_key.pub
        # or 
        # echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcPaIchJ5VuMX+/BT1uTuA9aiSME/z7Ev+YiV6aF5Nr9lZi0q2wOy1d424QmTITpEcOR3rmMQGUEMd4zv8mPvcee1bMV7g7xRvVtSs35KuedbIfchmdyQY8CARAJNHxMujzP0Sge7BJg/k2zDHTRFrCboLRiEdyb9xX6TseAMecH6x5/ixfoRyn7w+zqcbEO/BA0BmZqMdDet7Y/2tHJSmom8PupU5R/3Yu2+5RVL/zo6pzFKuxbgkKgkSDBLz5jvNGuutDgBLkDhc73VcwGWitloCm4KnRkXGHJZHmZxhhJakUhurLL6Vl1dyYUU6ITl1rK8TwlZW/FVPIppmvrDuwFh57USisg3sJQyXX/Ijr6JBz92O8Npkfj35LVMgCXKJksTAODqKQMKhUn4EFnAfhMu/gtjDyLWrjDJegrmV14Iazej2zWgK9s6MZS7WTX7x0F2xI69TzvoydU9LXZwhspH1z7dQMK3BK1YGjMJuxoXZna6QA9tyF66Y78CMKe/LciwickEzQZsDffjrpK4CKSzwfft4W7quTvkgaYja/cVjj3c0uEd++fJTYO4qHZylF6AiHnGAtqdZD2X3Fn1RhlVgelZNNFAhRfdQUEoS3iJJugzpwPsB6AhKlYFy7J0PzcJrhPVFWqsA110wuMC9usxfKW3wYmFEk2CBX9rAUw==" >> /home/ubuntu/.ssh/authorized_keys && \
      # Implement index.html
      # Implement git repo
      # Implement post-receive hooks
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt-get update && \
            apt-get install -y \
              python \
              nmap \
              vim \
              wget \
              python3-dev \
              git \
              apache2 && \
            echo "webserv1" > /etc/hostname && \
            echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcPaIchJ5VuMX+/BT1uTuA9aiSME/z7Ev+YiV6aF5Nr9lZi0q2wOy1d424QmTITpEcOR3rmMQGUEMd4zv8mPvcee1bMV7g7xRvVtSs35KuedbIfchmdyQY8CARAJNHxMujzP0Sge7BJg/k2zDHTRFrCboLRiEdyb9xX6TseAMecH6x5/ixfoRyn7w+zqcbEO/BA0BmZqMdDet7Y/2tHJSmom8PupU5R/3Yu2+5RVL/zo6pzFKuxbgkKgkSDBLz5jvNGuutDgBLkDhc73VcwGWitloCm4KnRkXGHJZHmZxhhJakUhurLL6Vl1dyYUU6ITl1rK8TwlZW/FVPIppmvrDuwFh57USisg3sJQyXX/Ijr6JBz92O8Npkfj35LVMgCXKJksTAODqKQMKhUn4EFnAfhMu/gtjDyLWrjDJegrmV14Iazej2zWgK9s6MZS7WTX7x0F2xI69TzvoydU9LXZwhspH1z7dQMK3BK1YGjMJuxoXZna6QA9tyF66Y78CMKe/LciwickEzQZsDffjrpK4CKSzwfft4W7quTvkgaYja/cVjj3c0uEd++fJTYO4qHZylF6AiHnGAtqdZD2X3Fn1RhlVgelZNNFAhRfdQUEoS3iJJugzpwPsB6AhKlYFy7J0PzcJrhPVFWqsA110wuMC9usxfKW3wYmFEk2CBX9rAUw==" >> /home/ubuntu/.ssh/authorized_keys && \
            wget https://raw.githubusercontent.com/pattonsgirl/Fall2020-CEG3120/master/Projects/Project2/index-serv1.html && \
            mv index-serv1.html /var/www/html/index.html && \
            sudo which git-shell >> /etc/shells && \
            adduser --quiet --disabled-password --shell /bin/bash --home /home/git --gecos "User" git && \
            mkdir /home/git/.ssh && \
            touch /home/git/.ssh/authorized_keys && \
            echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcPaIchJ5VuMX+/BT1uTuA9aiSME/z7Ev+YiV6aF5Nr9lZi0q2wOy1d424QmTITpEcOR3rmMQGUEMd4zv8mPvcee1bMV7g7xRvVtSs35KuedbIfchmdyQY8CARAJNHxMujzP0Sge7BJg/k2zDHTRFrCboLRiEdyb9xX6TseAMecH6x5/ixfoRyn7w+zqcbEO/BA0BmZqMdDet7Y/2tHJSmom8PupU5R/3Yu2+5RVL/zo6pzFKuxbgkKgkSDBLz5jvNGuutDgBLkDhc73VcwGWitloCm4KnRkXGHJZHmZxhhJakUhurLL6Vl1dyYUU6ITl1rK8TwlZW/FVPIppmvrDuwFh57USisg3sJQyXX/Ijr6JBz92O8Npkfj35LVMgCXKJksTAODqKQMKhUn4EFnAfhMu/gtjDyLWrjDJegrmV14Iazej2zWgK9s6MZS7WTX7x0F2xI69TzvoydU9LXZwhspH1z7dQMK3BK1YGjMJuxoXZna6QA9tyF66Y78CMKe/LciwickEzQZsDffjrpK4CKSzwfft4W7quTvkgaYja/cVjj3c0uEd++fJTYO4qHZylF6AiHnGAtqdZD2X3Fn1RhlVgelZNNFAhRfdQUEoS3iJJugzpwPsB6AhKlYFy7J0PzcJrhPVFWqsA110wuMC9usxfKW3wYmFEk2CBX9rAUw==" >> /home/git/.ssh/authorized_keys && \
            git init --bare /home/git/mastersite.git && \
            wget https://raw.githubusercontent.com/pattonsgirl/Fall2020-CEG3120/master/Projects/Project2/hooky && \
            mv hooky /home/git/mastersite.git/hooks/post-receive && \
            touch /home/git/mastersite.git/hooks/post-receive && \
            chmod a+x /home/git/mastersite.git/hooks/post-receive && \
            chown -R git /home/git/ && \
            chgrp -R git /home/git/ && \
            chown -R git /var/www/html && \
            chgrp -R git /var/www/html && \
            chmod 600 /home/ubuntu/.ssh/authorized_keys && \
            chown -R ubuntu /home/ubuntu/.ssh && \
            chgrp -R ubuntu /home/ubuntu/.ssh && \
            reboot
  Ubuntu2Instance:
    Type: 'AWS::EC2::Instance'
    DependsOn: AttachGateway
    Properties:
      ImageId: !FindInMap 
        - AWSRegionUbuntu
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref UbuntuInstanceType
          - Arch
      InstanceType: !Ref UbuntuInstanceType
      KeyName: !Ref KeyName
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG3120 Git
      NetworkInterfaces:
        - GroupSet:
            - !Ref LinuxSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref Subnet
          PrivateIpAddress: 10.0.0.25
      # Implement Meaningful conventions
      # Implement public key link for proxy
      # Implement index.html
      # Implement git repo
      # Implement post-receive hooks
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt-get update && \
            apt-get install -y \
              python \
              nmap \
              vim \
              wget \
              python3-dev \
              git \
              apache2 && \
            echo "webserv2" > /etc/hostname && \
            echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcPaIchJ5VuMX+/BT1uTuA9aiSME/z7Ev+YiV6aF5Nr9lZi0q2wOy1d424QmTITpEcOR3rmMQGUEMd4zv8mPvcee1bMV7g7xRvVtSs35KuedbIfchmdyQY8CARAJNHxMujzP0Sge7BJg/k2zDHTRFrCboLRiEdyb9xX6TseAMecH6x5/ixfoRyn7w+zqcbEO/BA0BmZqMdDet7Y/2tHJSmom8PupU5R/3Yu2+5RVL/zo6pzFKuxbgkKgkSDBLz5jvNGuutDgBLkDhc73VcwGWitloCm4KnRkXGHJZHmZxhhJakUhurLL6Vl1dyYUU6ITl1rK8TwlZW/FVPIppmvrDuwFh57USisg3sJQyXX/Ijr6JBz92O8Npkfj35LVMgCXKJksTAODqKQMKhUn4EFnAfhMu/gtjDyLWrjDJegrmV14Iazej2zWgK9s6MZS7WTX7x0F2xI69TzvoydU9LXZwhspH1z7dQMK3BK1YGjMJuxoXZna6QA9tyF66Y78CMKe/LciwickEzQZsDffjrpK4CKSzwfft4W7quTvkgaYja/cVjj3c0uEd++fJTYO4qHZylF6AiHnGAtqdZD2X3Fn1RhlVgelZNNFAhRfdQUEoS3iJJugzpwPsB6AhKlYFy7J0PzcJrhPVFWqsA110wuMC9usxfKW3wYmFEk2CBX9rAUw==" >> /home/ubuntu/.ssh/authorized_keys && \
            wget https://raw.githubusercontent.com/pattonsgirl/Fall2020-CEG3120/master/Projects/Project2/index-serv2.html && \
            mv index-serv2.html /var/www/html/index.html && \
            sudo which git-shell >> /etc/shells && \
            adduser --quiet --disabled-password --shell /bin/bash --home /home/git --gecos "User" git && \
            mkdir /home/git/.ssh && \
            touch /home/git/.ssh/authorized_keys && \
            echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcPaIchJ5VuMX+/BT1uTuA9aiSME/z7Ev+YiV6aF5Nr9lZi0q2wOy1d424QmTITpEcOR3rmMQGUEMd4zv8mPvcee1bMV7g7xRvVtSs35KuedbIfchmdyQY8CARAJNHxMujzP0Sge7BJg/k2zDHTRFrCboLRiEdyb9xX6TseAMecH6x5/ixfoRyn7w+zqcbEO/BA0BmZqMdDet7Y/2tHJSmom8PupU5R/3Yu2+5RVL/zo6pzFKuxbgkKgkSDBLz5jvNGuutDgBLkDhc73VcwGWitloCm4KnRkXGHJZHmZxhhJakUhurLL6Vl1dyYUU6ITl1rK8TwlZW/FVPIppmvrDuwFh57USisg3sJQyXX/Ijr6JBz92O8Npkfj35LVMgCXKJksTAODqKQMKhUn4EFnAfhMu/gtjDyLWrjDJegrmV14Iazej2zWgK9s6MZS7WTX7x0F2xI69TzvoydU9LXZwhspH1z7dQMK3BK1YGjMJuxoXZna6QA9tyF66Y78CMKe/LciwickEzQZsDffjrpK4CKSzwfft4W7quTvkgaYja/cVjj3c0uEd++fJTYO4qHZylF6AiHnGAtqdZD2X3Fn1RhlVgelZNNFAhRfdQUEoS3iJJugzpwPsB6AhKlYFy7J0PzcJrhPVFWqsA110wuMC9usxfKW3wYmFEk2CBX9rAUw==" >> /home/git/.ssh/authorized_keys && \
            git init --bare /home/git/mastersite.git && \
            touch /home/git/mastersite.git/hooks/post-receive && \
            chmod a+x /home/git/mastersite.git/hooks/post-receive && \
            wget https://raw.githubusercontent.com/pattonsgirl/Fall2020-CEG3120/master/Projects/Project2/hooky && \
            mv hooky /home/git/mastersite.git/hooks/post-receive && \
            chown -R git /home/git/ && \
            chgrp -R git /home/git/ && \
            chown -R git /var/www/html && \
            chgrp -R git /var/www/html && \
            chmod 600 /home/ubuntu/.ssh/authorized_keys && \
            chown -R ubuntu /home/ubuntu/.ssh && \
            chgrp -R ubuntu /home/ubuntu/.ssh && \
            reboot
  Ubuntu3Instance:
    Type: 'AWS::EC2::Instance'
    DependsOn: AttachGateway
    Properties:
      ImageId: !FindInMap 
        - AWSRegionUbuntu
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref UbuntuInstanceType
          - Arch
      InstanceType: !Ref UbuntuInstanceType
      KeyName: !Ref KeyName
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG3120 HAProxy
      NetworkInterfaces:
        - GroupSet:
            - !Ref LinuxSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref Subnet
          PrivateIpAddress: 10.0.0.100
      # Implement Meaningful conventions
      #  TODO: Quietly produce public/private keypairs
      #  TODO:  sftp put key into git-server and ldap-server's authorized_keys
      # Configure .ssh/config file 
      # Configure directory/file permissions 
      # Configure HAProxy Load Balancer
      # Initialize bare bones git repository
      # Removing:  touch /home/ubuntu/repository/.git/hooks/post-receive && \
      # echo "scp  /home/ubuntu/repository/index.html webserv1:/var/www/html/index.html" >> /home/ubuntu/repository/.git/hooks/post-receive && \
      # echo "scp  /home/ubuntu/repository/index.html webserv2:/var/www/html/index.html" >> /home/ubuntu/repository/.git/hooks/post-receive && \      
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt-get update && \
            apt-get install -y \
              python \
              nmap \
              vim \
              wget \
              python3-dev \
              haproxy \
              git \
              apache2 && \
            echo "proxy-server" > /etc/hostname && \
            echo -e "10.0.0.20\t webserv1" >> /etc/hosts && \
            echo -e "10.0.0.25\t webserv2" >> /etc/hosts && \
            echo "-----BEGIN RSA PRIVATE KEY-----" >>  /home/ubuntu/.ssh/haproxy_key && \
            echo "PRIVATE-KEY-REQUIRED" >>  /home/ubuntu/.ssh/haproxy_key && \
            echo "-----END RSA PRIVATE KEY-----" >>  /home/ubuntu/.ssh/haproxy_key && \
            chmod 600 /home/ubuntu/.ssh/haproxy_key && \
            touch /home/ubuntu/.ssh/config && \
            echo "# Identify file for SSH" >> /home/ubuntu/.ssh/config && \
            echo "# Host [IP/DNS]" >> /home/ubuntu/.ssh/config && \
            echo -e "#\t Identity File [/path/to/private/key]" >> /home/ubuntu/.ssh/config && \
            echo "Host webserv1" >> /home/ubuntu/.ssh/config && \
            echo -e "\tIdentityFile ~/.ssh/haproxy_key" >> /home/ubuntu/.ssh/config && \
            echo "Host webserv2" >> /home/ubuntu/.ssh/config && \
            echo -e "\tIdentityFile ~/.ssh/haproxy_key" >> /home/ubuntu/.ssh/config && \
            mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.original && \
            wget https://raw.githubusercontent.com/pattonsgirl/Fall2020-CEG3120/master/Projects/Project2/haproxy.cfg && \
            mv haproxy.cfg /etc/haproxy/haproxy.cfg && \
            chown -R ubuntu /etc/haproxy && \
            chgrp -R ubuntu /etc/haproxy && \
            chown -R ubuntu /home/ubuntu/ && \
            chgrp -R ubuntu /home/ubuntu/ && \
            service haproxy start && \
            reboot
